### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by keflavich**
Some of the code had become obsolete with the release of reproject.  I'm also
attempting to fix some of the documentation, which has failed for unknown
reasons.

### CODE REVIEW

**Comment by keflavich** [comment]
Build failures are from https://github.com/astropy/package-template/issues/126

**Comment by keflavich** [comment]
@bsipocz not your job, but do you have any idea why I'm getting so many sphinx warnings?  They're mostly variations on the theme of:
```
None:None: WARNING: toctree contains reference to nonexisting document 'api/image_registration.fft_tools.convolve_nd.fftn'
```
I don't know why that document is being referred to and/or not generated.

**Comment by bsipocz** [comment]
@keflavich - I vaguely remember seeing similar warning, but can't remember the solution for sure but can try a few things.

**Comment by bsipocz** [comment]
Ok, I think I figured out the problem. 
If there is no __all__ defined then every function gets included in the API docs including the ones that got imported to that namespace. Naturally sphinx can't find any docstring for those to generate the api docs from. 
Also I've opted out to list the test functions in the API index.

There are however 3 warnings remaining. I'm not sure what's the problem there, but something doesn't work as it should, e.g. files with the extension ``automodapi`` are generated, and I can't recall that's happening in other packages.

**Comment by bsipocz** [comment]
Well, those 3 could be fixed by adding ``:noindex:`` for the second entries.

**Comment by keflavich** [comment]
the remaining warnings are all in astropy-helpers, so I think they'll go away eventually...

**Comment by bsipocz** [comment]
Updating the helpers to v1.3 should solve those (that's why I had the update in the PR above)

**Comment by keflavich** [comment]
yes, I merged that into this PR, so it should have resolved the issues here too

**Comment by keflavich** [comment]
oh, unless my "update" undid it? hrm.

**Comment by bsipocz** [comment]
yep, probably it did.

**Pull request merged**
